FROM centos:centos7

ENV GOPATH /root
ENV TARGET /root/src/github.com/funbox/init-exporter

RUN yum install -y http://release.yum.kaos.io/i386/kaos-repo-1.2.0-0.el6.noarch.rpm
RUN yum clean all && yum -y update

RUN yum -y install make go

COPY . $TARGET
RUN ls $TARGET -al
RUN cd $TARGET && make all && make install

RUN useradd service
RUN mkdir -p /var/local/init-exporter/helpers && mkdir -p /var/log/init-exporter

COPY ./testdata /root

RUN yum clean all && rm -rf /tmp/*

WORKDIR /root
